spring.application.name=date_night_arcade

spring.datasource.url=jdbc:mysql://localhost:3306/DateNightAtTheArcade?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://dpg-ctqdn5q3esus73drhs70-a.oregon-postgres.render.com/datenightatthearcade
#spring.datasource.username=datenightatthearcade_user
#spring.datasource.password=v1Pr7wbTNSC9u8zGA18pkOiGMZYjjHG3

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver





